name: "TicTacToe Frontend CI"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 
        run: |
          echo "Install dependencies"
          npm install
          echo "Deploy app to netlify"
          npm run build
          echo "Run tests"
          npm test
